I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 64, in script call
    call mechanical_floor_1 from _call_mechanical_floor_1
  File "game/endings.rpy", line 259, in script
    if insanity_level >= 1:
  File "game/endings.rpy", line 261, in <module>
    elif insanity >= 2:
NameError: name 'insanity' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 64, in script call
    call mechanical_floor_1 from _call_mechanical_floor_1
  File "game/endings.rpy", line 259, in script
    if insanity_level >= 1:
  File "C:\Games\Renpy SDK\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "C:\Games\Renpy SDK\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Games\Renpy SDK\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/endings.rpy", line 261, in <module>
    elif insanity >= 2:
NameError: name 'insanity' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Cafe of The Dead 1.1
Sun Jun 29 16:22:52 2025
